import "./globals.css";
import { GlobalProvider } from "@/context/GlobalContext";
import Nav from "@/components/Nav";
import DisplayAI from "@/components/DisplayAI";
import Footer from "@/components/Footer";
import WaitlistModal from "@/components/WaitlistModal";
import { ToastContainer } from "react-toastify";

const metadata = {
  title: "NearSwipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className="bg-black">
        <GlobalProvider>
          <Nav />
          <WaitlistModal />
          {children}
          <DisplayAI />
          <Footer />
          <ToastContainer  />
        </GlobalProvider>
      </body>
    </html>
  );
}
