"use client";
import Footer from "@/components/Footer";
import "./globals.css";
import Nav from "@/components/Nav";
import { useState } from "react";
import { GlobalProvider } from "@/context/GlobalContext";

const metadata = {
  title: "NearSwipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <GlobalProvider>
          <Nav />

          {children}

          <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
